version: '1'
services:
  static:
    image: envoyproxy/envoy:v1.22.5
    restart: always
    ports:
      - "9000:80"
      - "9443:443"
    volumes:
      - ./envoy/static:/etc/envoy:ro
  dynamic:
    image: envoyproxy/envoy:v1.22.5
    restart: always
    ports:
      - "6000:80"
      - "6443:443"
    volumes:
      - ./envoy/dynamic:/etc/envoy:ro